### ISSUE TITLE
Should we still install GalliumOS?  any hope/chance for ChromeOS Flex support?

### ISSUE THREAD

**Issue by alanhoyle** [reynhout/chrx#143]
It appears that this project hasn't had any updates for a few years (3 years as of early 2023).  It also appears that GalliumOS hasn't had any updates and is no longer being developed (see various threads at https://www.reddit.com/r/GalliumOS/).  I suspect this means we shouldn't install that anymore.  

Is there any chance that this could be updated to allow easy installation of ChromeOS Flex?

**Comment by alanhoyle** [comment]
FWIW, I was able to install Lubuntu easily, and it works fine after some minor interface tweaks on my HP 13-G1 with a highDPI display.  (it worked without the tweaks, but the text was too small most of the time.

**Comment by cuvtixo** [comment]
so, your answer is, no? lol Lubuntu's been pretty good with continued
updates.

**Comment by cuvtixo** [comment]
I've been in similar situations, like back when mkLinux was the best linux
for PowerPC Macs for a while(actually it's kernel was a custom microkernel,
so not actually "linux" according to the diehards), but then more generic
PPC Linuxes (with actual linux kernels) brought advantages because they
continued developing when MK ceased. This is all part of the nature of the
evolution of Open Source development. Sometimes you get a shark, that seems
purposefully designed, and sometimes you get a platypus. If you knew
old Neverware’s
CloudReady, which pre-dated Flex, but never had the resources to catch up
to normal ChromeOS development, and the increasing attention to ARM... I'm
not sure what you're looking for from a Flex installer. To be used on
earlier models? As much as I love extending the life of old Chromebooks,
they weren't meant to last long and I think this doomed GalliumOS

**Comment by alanhoyle** [comment]
At least partly why I'm posting this is that there seems to be little documentation that development on GalliumOS ended a few years ago, so people who use `chrx` to install might want to be aware of that.  

I only know because of posts on the r/GalliumOS subreddit and noticing that I didn't get any updates on my install.  [GalliumOS.org ](https://galliumos.org/)is still up, but no "news" has been posted since December 2019, and the [GalliumOS Twitter](https://twitter.com/GalliumOS) hasn't posted since 2018.

**Comment by spoelstraethan** [comment]
ChromeOS Flex works well with the MrChromebox full UEFI firmware, and if your base ChromeOS is outdated due to AUE being past you may want to install the MrChromebox full UEFI to get a modern bootloader with less bugs.

Otherwise you could potentially set the GBB flags to force enable booting from USB and unsigned/devsigned kernels and then replace ChromeOS with ChromeOS Flex, but I haven't tried that yet, mostly because I just thought of it based on recent experiences with postmarketOS (which I'm also hoping to figure out a way to install via Chrx in a semi-automated fashion).

**Comment by alanhoyle** [comment]
I forgot I had posted  this issue.  

I ended up installing the MrChromebox.tech full UEFI firmware on my AUE expired HP Chromebook 13 G1.  Seems to work fine, and has much less trouble with the HiDPI display than GalliumOS ever had.  

If there's another lightweight Linux distro that has good support for HiDPI displays without tons of tweaking, I'd still love to know about it, but in the meantime, I'd avoid GalliumOS and go with MrChromebox and ChromeOS Flex or another distro.

**Comment by spoelstraethan** [comment]
I'm a big fan of the philosophy of postmarketOS, their goal is to have
support for almost all devices possible integrated into the mainstream
Linux kernel which in turn gives them a much longer lifetime than if every
update for a given device requires going back in time to end Google or the
manufacturer forked the kernel to have a stable branch to build on top of
until things could be submitted upstream. Some of the manufacturers never
end up submitting those patches upstream because there's a certain standard
of code quality required for the kernel and they don't always want to put
in that effort.

There is a generic x86_64 Chromebook kernel available that so far seems to
be working on the devices I've tested on. I actually started looking at
postmarketOS because it had support for the ARM systems that chrx doesn't
fully work with, and it knocks out of the park for ARMv7 and ARM64 aka
aarch64 systems.
