### ISSUE TITLE
Any ideas on supporting Toshiba CB35 Chromebooks?

### ISSUE THREAD

**Issue by toranb** [reynhout/chrx#2]
First up -thanks for taking the time to write/maintain/own this very useful script. I volunteer once each summer and give each of the 8 students a free Chromebook so they can continue hacking on python long after I'm gone and it would be possible w/out efforts like this one!

I'm unsure if it's a true bios issue or something else but when the Toshiba boots and I hit control + l the machine beeps twice and fails to boot into what looks like a valid ubuntu or xubuntu install using this most excellent script.

Any idea what log I can dig into that would show why this fails to boot after the install?

**Comment by reynhout** [comment]
That sounds like a great project you're working on!

I can't say for sure what the problem is, but since it happens so early it might be due to some kernel configuration that is tweaked for Acer C720s.

I recently added a command line switch to skip those customization steps and install the stock OS only. Now that Ubuntu "latest" delivers a kernel with support for many/most Chromebooks, this might be enough to boot successfully.

To give it a try, just add the `-s` switch to your command line. E.g.: 

    curl -Oks https://chrx.org/go && sh go -s

If that works, you might still need some config tweaks to get everything working well, but it'd be a huge step forward at least.

I'd love to incorporate fixes for the CB35, so if you get a chance to test, please keep me updated!

**Comment by toranb** [comment]
Sorry for the delay - I used the command below but sadly no dice :(

```
curl -Oks https://chrx.org/go && sh go -s
```

I decided to punt for now but if at some point I can buy one of these myself I'd love to hack on this script so we can support next gen chromebooks :)
