### ISSUE TITLE
sda1 turns into sda11

### ISSUE THREAD

**Issue by tocantonto** [reynhout/chrx#73]
I have tried with two different USB flash drives on my CELES.  When running the chrx script it bogs at the formatting portion with the following error:
-------------------------------
Installing to target disk /dev/sda1

  WARNING: All data on /dev/sda1 will be erased!
           Continue at your own risk!

Press [enter] to continue or CTRL-C to quit: 
Setting up target disk /dev/sda1 formatting...
Disk /dev/sda1: 61.9 GiB, 66409463808 bytes, 129705984 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C9B44F55-B84A-F24C-9A91-641A3CBE2021

Device      Start       End   Sectors  Size Type
/dev/sda1p1  2048 129705950 129703903 61.9G Linux filesystem
OK

Installing to /dev/sda11...
The file /dev/sda11 does not exist and no size was specified.
fatal: return code 1 from command "mkfs.ext4 -q /dev/sda11"
-------------------------------

The command used was 
-------------------------------
cd ; curl -Os https://chrx.org/go && sh go -t /dev/sda1 -d galliumos -m ca1.us -r nightly -H bismouth -U tocantonto -p dev-misc -Z America/Los_Angeles
-------------------------------

Does chrx only work if installed to the whole device rather than a partition?  
THANKS

**Comment by reynhout** [comment]
@tocantonto We should do more to catch that error, but yep -- the working syntax is `-t /dev/sda`, instead of `-t /dev/sda1` (so yes, specify the **disk** device, not the **partition** device).

It would also be reasonable to try to install to specific partitions (external media only), but the code does not do so.

PS: A couple minor items:

* The `ca1.us` mirror might be down :(
* You've misspelled "bismuth", if that is your goal :)
* `-d galliumos` is not required (is default)
* If you want GalliumOS 3.0 Bismuth (recommended!), you need the `-r dev` flag

**Comment by tocantonto** [comment]
Thanks for all the good information.
Intentional play with the name.  My 3.0 Bismuth install is a little weird, so i'm trying a nightly install.
Cheers!
